# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package structure to make it clearer which packages are bundled with Android OS.
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete".
kotlin.code.style=official

# Disable resource/BuildConfig features not used, keep build lean.
android.defaults.buildfeatures.buildconfig=false
android.nonTransitiveRClass=true
android.nonFinalResIds=false
