-- NiñoBiólogo: Vida en Miniatura — datos semilla reales
-- Generado por tools/generate_seed_data.py. El contenido completo se inserta en tiempo de
-- ejecución por DatabaseSeeder.kt a partir de SeedContent.kt (misma fuente de datos).

-- Ambientes (5/5)
INSERT INTO microscopic_environments (id, orderIndex, name, tagline, description, iconKey, primaryColorHex, secondaryColorHex) VALUES ('micromundo', 1, 'Micromundo', 'Un universo invisible en cada gota', 'Analiza muestras de agua y descubre la vida microscópica que flota en ellas.', 'env_micromundo', '#5B8C5A', '#DCEFDC');
INSERT INTO microscopic_environments (id, orderIndex, name, tagline, description, iconKey, primaryColorHex, secondaryColorHex) VALUES ('bosque_de_vida', 2, 'Bosque de Vida', 'Naturaleza para observar de cerca', 'Recoge hojas, cortezas y huellas del bosque para examinarlas en el laboratorio.', 'env_bosque', '#2E7D32', '#E3F2E1');
INSERT INTO microscopic_environments (id, orderIndex, name, tagline, description, iconKey, primaryColorHex, secondaryColorHex) VALUES ('oceano_profundo', 3, 'Océano Profundo', 'Muestras traídas desde el mar', 'Examina muestras de agua salada, arrecifes y restos marinos en tu laboratorio.', 'env_oceano', '#0277BD', '#E1F5FE');
INSERT INTO microscopic_environments (id, orderIndex, name, tagline, description, iconKey, primaryColorHex, secondaryColorHex) VALUES ('cuerpo_humano', 4, 'Cuerpo Humano', 'Un laboratorio viviente', 'Observa muestras de células y tejidos para entender cómo funciona tu cuerpo.', 'env_cuerpo', '#C62828', '#FDE8E8');
INSERT INTO microscopic_environments (id, orderIndex, name, tagline, description, iconKey, primaryColorHex, secondaryColorHex) VALUES ('ecosistemas', 5, 'Ecosistemas', 'Todo está conectado', 'Investiga muestras de tierra y agua para descubrir cómo se relacionan los seres vivos.', 'env_ecosistemas', '#EF6C00', '#FFF3E0');

-- Muestras (20/20)
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_micromundo_01', 'micromundo', 1, 'Gota de agua de charca', 'Recogida en una charca del jardín', 1, 'sample_micromundo_01');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_micromundo_02', 'micromundo', 2, 'Agua con luz de sol', 'Tomada de un estanque bien iluminado', 1, 'sample_micromundo_02');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_micromundo_03', 'micromundo', 3, 'Trozo de masa de pan', 'Guardada en un frasco durante dos días', 2, 'sample_micromundo_03');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_micromundo_04', 'micromundo', 4, 'Musgo húmedo', 'Recogido junto a una roca húmeda', 2, 'sample_micromundo_04');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_bosque_de_vida_01', 'bosque_de_vida', 1, 'Hojarasca del suelo', 'Recogida bajo un helecho del bosque', 1, 'sample_bosque_de_vida_01');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_bosque_de_vida_02', 'bosque_de_vida', 2, 'Huellas junto al arroyo', 'Encontradas cerca de un arroyo del bosque', 1, 'sample_bosque_de_vida_02');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_bosque_de_vida_03', 'bosque_de_vida', 3, 'Ala caída', 'Encontrada sobre una hoja del sendero', 2, 'sample_bosque_de_vida_03');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_bosque_de_vida_04', 'bosque_de_vida', 4, 'Plumas y pelos nocturnos', 'Recogidos en un claro del bosque de noche', 2, 'sample_bosque_de_vida_04');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_oceano_profundo_01', 'oceano_profundo', 1, 'Agua de un charco de marea', 'Tomada de un charco dejado por la marea baja', 1, 'sample_oceano_profundo_01');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_oceano_profundo_02', 'oceano_profundo', 2, 'Trozo de arrecife', 'Recogido cerca de un arrecife de coral', 1, 'sample_oceano_profundo_02');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_oceano_profundo_03', 'oceano_profundo', 3, 'Rastro de tinta', 'Observado tras un encuentro con un pulpo', 2, 'sample_oceano_profundo_03');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_oceano_profundo_04', 'oceano_profundo', 4, 'Grabación submarina', 'Un hidrófono capturó este sonido en altamar', 2, 'sample_oceano_profundo_04');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_cuerpo_humano_01', 'cuerpo_humano', 1, 'Gota de sangre', 'Tomada con una lanceta segura de laboratorio', 1, 'sample_cuerpo_humano_01');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_cuerpo_humano_02', 'cuerpo_humano', 2, 'Muestra de tejido nervioso', 'Modelo de laboratorio del sistema nervioso', 1, 'sample_cuerpo_humano_02');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_cuerpo_humano_03', 'cuerpo_humano', 3, 'Fibra muscular', 'Modelo de laboratorio de tejido muscular', 2, 'sample_cuerpo_humano_03');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_cuerpo_humano_04', 'cuerpo_humano', 4, 'Muestra de una herida en curación', 'Modelo de laboratorio de coagulación', 2, 'sample_cuerpo_humano_04');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_ecosistemas_01', 'ecosistemas', 1, 'Muestra de pasto', 'Recogida en la sabana tras la lluvia', 1, 'sample_ecosistemas_01');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_ecosistemas_02', 'ecosistemas', 2, 'Pelo junto a un rastro', 'Encontrado junto a huellas de un gran felino', 1, 'sample_ecosistemas_02');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_ecosistemas_03', 'ecosistemas', 3, 'Hoja flotante', 'Tomada de la superficie de un estanque', 2, 'sample_ecosistemas_03');
INSERT INTO scientific_samples (id, environmentId, orderIndex, name, origin, difficulty, iconKey) VALUES ('sample_ecosistemas_04', 'ecosistemas', 4, 'Madera en descomposición', 'Recogida del suelo húmedo del bosque', 2, 'sample_ecosistemas_04');

-- Descubrimientos (30/30)
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_paramecio', 'sample_micromundo_01', 'micromundo', 'Paramecio', 'Paramecium caudatum', 'MICROORGANISMO', 'Agua dulce estancada', 'Bacterias y algas microscópicas', 'forma de zapatilla|se mueve con cilios|unicelular', 'Puede expulsar el agua que le sobra con una estructura llamada vacuola contráctil.', 'COMUN', 'disc_paramecio');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_ameba', 'sample_micromundo_01', 'micromundo', 'Ameba', 'Amoeba proteus', 'MICROORGANISMO', 'Estanques y suelos húmedos', 'Bacterias y otros microorganismos', 'cambia de forma constantemente|se mueve con seudópodos|unicelular', 'No tiene una forma fija: la cambia para moverse y para atrapar su alimento.', 'COMUN', 'disc_ameba');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_euglena', 'sample_micromundo_02', 'micromundo', 'Euglena', 'Euglena viridis', 'MICROORGANISMO', 'Agua dulce con luz', 'Fotosíntesis y también absorbe nutrientes', 'tiene un flagelo|un ojo sensible a la luz|verde por clorofila', 'Es mitad planta, mitad animal: hace fotosíntesis pero también nada activamente.', 'POCO_COMUN', 'disc_euglena');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_levadura', 'sample_micromundo_03', 'micromundo', 'Levadura', 'Saccharomyces cerevisiae', 'HONGO', 'Frutas maduras y masas de pan', 'Azúcares', 'unicelular|se reproduce por gemación|produce burbujas de gas', 'Es la responsable de que el pan suba y de que crezca la espuma en algunas bebidas.', 'COMUN', 'disc_levadura');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_tardigrado', 'sample_micromundo_04', 'micromundo', 'Tardígrado', 'Milnesium tardigradum', 'ANIMAL', 'Musgos húmedos', 'Líquidos de plantas y microorganismos', 'ocho patas diminutas|resiste el espacio exterior|se llama ''oso de agua''', 'Puede sobrevivir congelado, deshidratado e incluso en el vacío del espacio.', 'RARO', 'disc_tardigrado');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_diatomea', 'sample_micromundo_02', 'micromundo', 'Diatomea', 'Bacillariophyta', 'MICROORGANISMO', 'Océanos y lagos', 'Fotosíntesis', 'caparazón de vidrio (sílice)|produce gran parte del oxígeno del planeta|forma parte del plancton', 'Las diatomeas producen alrededor de una quinta parte del oxígeno que respiramos.', 'POCO_COMUN', 'disc_diatomea');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_volvox', 'sample_micromundo_04', 'micromundo', 'Volvox', 'Volvox globator', 'MICROORGANISMO', 'Estanques y charcas', 'Fotosíntesis', 'forma colonias esféricas|miles de células trabajando juntas|gira al nadar', 'Aunque es diminuto, el Volvox forma colonias que giran juntas como una pequeña esfera verde.', 'RARO', 'disc_volvox');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_helecho', 'sample_bosque_de_vida_01', 'bosque_de_vida', 'Helecho gigante', 'Polypodiopsida', 'PLANTA', 'Bosque húmedo', 'Fotosíntesis', 'hojas grandes y divididas|se reproduce por esporas|no tiene flores', 'Los helechos existían en la Tierra mucho antes que los dinosaurios.', 'COMUN', 'disc_helecho');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_seta_amanita', 'sample_bosque_de_vida_01', 'bosque_de_vida', 'Seta roja', 'Amanita muscaria', 'HONGO', 'Bosques de coníferas', 'Materia orgánica en descomposición', 'sombrero rojo con puntos blancos|no debe tocarse ni comerse|ayuda a reciclar nutrientes', 'Los hongos no son plantas: forman su propio reino y reciclan la materia del bosque.', 'POCO_COMUN', 'disc_seta');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_conejo', 'sample_bosque_de_vida_02', 'bosque_de_vida', 'Conejo silvestre', 'Oryctolagus cuniculus', 'ANIMAL', 'Praderas y bosques', 'Pasto y hierbas', 'orejas largas|excelente oído|se reproduce rápidamente', 'Un conejo puede girar sus orejas de forma independiente para escuchar en dos direcciones.', 'COMUN', 'disc_conejo');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_zorro', 'sample_bosque_de_vida_02', 'bosque_de_vida', 'Zorro rojo', 'Vulpes vulpes', 'ANIMAL', 'Bosques y zonas mixtas', 'Roedores, conejos e insectos', 'cola espesa|muy adaptable|caza principalmente de noche', 'El zorro puede detectar el campo magnético de la Tierra para calcular sus saltos al cazar.', 'POCO_COMUN', 'disc_zorro');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_mariposa', 'sample_bosque_de_vida_03', 'bosque_de_vida', 'Mariposa monarca', 'Danaus plexippus', 'ANIMAL', 'Praderas y bosques', 'Néctar de flores', 'migra miles de kilómetros|colores naranja y negro|se transforma desde oruga', 'Puede migrar más de 4.000 kilómetros usando el sol como brújula.', 'RARO', 'disc_mariposa');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_buho', 'sample_bosque_de_vida_04', 'bosque_de_vida', 'Búho real', 'Bubo bubo', 'ANIMAL', 'Bosques y acantilados', 'Roedores y aves pequeñas', 'vuelo silencioso|gira la cabeza casi 270°|vista nocturna excelente', 'Sus plumas especiales le permiten volar sin hacer casi ningún ruido.', 'POCO_COMUN', 'disc_buho');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_lince', 'sample_bosque_de_vida_04', 'bosque_de_vida', 'Lince ibérico', 'Lynx pardinus', 'ANIMAL', 'Bosque mediterráneo', 'Conejos principalmente', 'orejas con mechones de pelo|vista y oído extraordinarios|especie protegida', 'Es uno de los felinos más amenazados del mundo, y gracias a la protección va recuperándose.', 'LEGENDARIO', 'disc_lince');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_alga_marina', 'sample_oceano_profundo_02', 'oceano_profundo', 'Alga parda gigante', 'Macrocystis pyrifera', 'PLANTA', 'Bosques submarinos', 'Fotosíntesis', 'puede crecer más de 30 metros|forma auténticos bosques bajo el agua|crece muy rápido', 'Puede crecer hasta 50 centímetros en un solo día bajo condiciones ideales.', 'COMUN', 'disc_alga');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_coral', 'sample_oceano_profundo_02', 'oceano_profundo', 'Coral cerebro', 'Diploria labyrinthiformis', 'ANIMAL', 'Arrecifes tropicales', 'Plancton y luz solar (con algas asociadas)', 'forma colonias de miles de individuos|construye el esqueleto del arrecife|vive en simbiosis con algas', 'Un arrecife de coral puede albergar más especies distintas que cualquier otro ecosistema marino.', 'POCO_COMUN', 'disc_coral');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_medusa', 'sample_oceano_profundo_01', 'oceano_profundo', 'Medusa luna', 'Aurelia aurita', 'ANIMAL', 'Aguas costeras', 'Plancton', 'cuerpo casi transparente|se mueve con pulsaciones|no tiene cerebro ni corazón', 'Está formada en un 95% por agua y existe desde antes que los dinosaurios.', 'POCO_COMUN', 'disc_medusa');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_pulpo', 'sample_oceano_profundo_03', 'oceano_profundo', 'Pulpo común', 'Octopus vulgaris', 'ANIMAL', 'Fondos rocosos', 'Cangrejos y moluscos', 'ocho brazos con ventosas|cambia de color y textura|extremadamente inteligente', 'Tiene tres corazones y su sangre es de color azul.', 'RARO', 'disc_pulpo');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_estrella_mar', 'sample_oceano_profundo_01', 'oceano_profundo', 'Estrella de mar', 'Asteroidea', 'ANIMAL', 'Fondos marinos', 'Moluscos y materia orgánica', 'puede regenerar brazos perdidos|no tiene cerebro|se mueve con cientos de piececillos', 'Si pierde un brazo, puede regenerarlo por completo con el paso del tiempo.', 'POCO_COMUN', 'disc_estrella');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_pez_payaso', 'sample_oceano_profundo_03', 'oceano_profundo', 'Pez payaso', 'Amphiprioninae', 'ANIMAL', 'Arrecifes de coral', 'Algas y pequeños invertebrados', 'vive protegido entre las anémonas|es inmune a su veneno|cambia de sexo durante su vida', 'Vive en una relación de ayuda mutua con la anémona: ella lo protege y él la limpia.', 'POCO_COMUN', 'disc_pez_payaso');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_ballena_azul', 'sample_oceano_profundo_04', 'oceano_profundo', 'Ballena azul', 'Balaenoptera musculus', 'ANIMAL', 'Océano abierto', 'Kril (pequeños crustáceos)', 'el animal más grande del planeta|corazón del tamaño de un auto pequeño|canta bajo el agua', 'A pesar de ser gigantesca, se alimenta de uno de los animales más pequeños del mar: el kril.', 'LEGENDARIO', 'disc_ballena');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_globulo_rojo', 'sample_cuerpo_humano_01', 'cuerpo_humano', 'Glóbulo rojo', 'Erythrocyte', 'MICROORGANISMO', 'Torrente sanguíneo', 'No se alimenta: transporta oxígeno', 'forma de disco|transporta oxígeno por el cuerpo|no tiene núcleo', 'Tu cuerpo produce alrededor de dos millones de glóbulos rojos nuevos cada segundo.', 'COMUN', 'disc_globulo_rojo');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_globulo_blanco', 'sample_cuerpo_humano_01', 'cuerpo_humano', 'Glóbulo blanco', 'Leukocyte', 'MICROORGANISMO', 'Torrente sanguíneo', 'Bacterias y microbios invasores', 'defiende al cuerpo de infecciones|puede salir de los vasos sanguíneos|existen varios tipos', 'Son los soldados del sistema inmunitario: patrullan el cuerpo buscando invasores.', 'POCO_COMUN', 'disc_globulo_blanco');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_neurona', 'sample_cuerpo_humano_02', 'cuerpo_humano', 'Neurona', 'Neuron', 'MICROORGANISMO', 'Cerebro y sistema nervioso', 'Glucosa y oxígeno', 'se comunica con impulsos eléctricos|tiene ramificaciones llamadas dendritas|forma redes complejísimas', 'El cerebro humano tiene unos 86.000 millones de neuronas conectadas entre sí.', 'RARO', 'disc_neurona');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_celula_muscular', 'sample_cuerpo_humano_03', 'cuerpo_humano', 'Célula muscular', 'Myocyte', 'MICROORGANISMO', 'Músculos del cuerpo', 'Glucosa y oxígeno', 'se contrae para generar movimiento|puede alargarse mucho|trabaja en equipo con otras fibras', 'Algunas células musculares pueden medir varios centímetros de largo, muy alargadas.', 'POCO_COMUN', 'disc_celula_muscular');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_plaqueta', 'sample_cuerpo_humano_04', 'cuerpo_humano', 'Plaqueta', 'Thrombocyte', 'MICROORGANISMO', 'Torrente sanguíneo', 'No se alimenta: repara heridas', 'ayuda a cerrar heridas|es más pequeña que un glóbulo rojo|forma coágulos', 'Cuando te cortas, miles de plaquetas corren al lugar para taponar la herida en minutos.', 'COMUN', 'disc_plaqueta');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_pasto', 'sample_ecosistemas_01', 'ecosistemas', 'Pasto de sabana', 'Poaceae', 'PLANTA', 'Sabana africana', 'Fotosíntesis', 'crece rápido tras la lluvia|base de la cadena en la sabana|resiste el pisoteo', 'La sabana puede sostener manadas enteras de herbívoros gracias a su rápido crecimiento.', 'COMUN', 'disc_pasto');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_leon', 'sample_ecosistemas_02', 'ecosistemas', 'León', 'Panthera leo', 'ANIMAL', 'Sabana africana', 'Cebras, ñus y otros herbívoros', 'vive en manadas llamadas orgullos|las hembras cazan en equipo|es el depredador tope de la sabana', 'Las leonas hacen la mayoría de las cacerías, a menudo trabajando en equipo.', 'POCO_COMUN', 'disc_leon');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_nenufar', 'sample_ecosistemas_03', 'ecosistemas', 'Nenúfar', 'Nymphaea', 'PLANTA', 'Estanque de agua dulce', 'Fotosíntesis', 'hojas flotantes|raíces ancladas al fondo|flores que se abren de día', 'Sus hojas flotantes son tan resistentes que pueden sostener el peso de una pequeña rana.', 'COMUN', 'disc_nenufar');
INSERT INTO microscope_discoveries (id, sampleId, environmentId, name, scientificName, category, habitat, diet, characteristics, curiosity, rarity, iconKey) VALUES ('disc_hongo_reciclador', 'sample_ecosistemas_04', 'ecosistemas', 'Hongo reciclador de estanque', 'Saprolegnia sp.', 'HONGO', 'Estanque de agua dulce', 'Materia orgánica en descomposición', 'descompone restos de plantas y animales|libera nutrientes de vuelta al agua|invisible a simple vista en su mayoría', 'Sin descomponedores como este hongo, los nutrientes nunca volverían a estar disponibles.', 'POCO_COMUN', 'disc_hongo_reciclador');

-- Modelos de célula (3) y estructuras (11)
INSERT INTO cell_models (id, name, cellType, description) VALUES ('cell_animal', 'Célula animal', 'Animal', 'La unidad básica de todos los animales, incluido tú.');
INSERT INTO cell_models (id, name, cellType, description) VALUES ('cell_vegetal', 'Célula vegetal', 'Vegetal', 'La unidad básica de todas las plantas del Bosque de Vida.');
INSERT INTO cell_models (id, name, cellType, description) VALUES ('cell_bacteriana', 'Célula bacteriana', 'Bacteriana', 'Mucho más simple: no tiene núcleo definido.');
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_animal_nucleo', 'cell_animal', 'Núcleo', 'Controla las actividades de la célula y guarda el ADN.', 0.5, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_animal_membrana', 'cell_animal', 'Membrana celular', 'Protege la célula y controla lo que entra y sale.', 0.12, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_animal_citoplasma', 'cell_animal', 'Citoplasma', 'Sustancia gelatinosa donde ocurren las reacciones de la célula.', 0.3, 0.75);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_animal_mitocondria', 'cell_animal', 'Mitocondria', 'Genera la energía que la célula necesita para funcionar.', 0.7, 0.3);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_vegetal_nucleo', 'cell_vegetal', 'Núcleo', 'Controla las actividades de la célula y guarda el ADN.', 0.5, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_vegetal_pared', 'cell_vegetal', 'Pared celular', 'Capa rígida que da forma y soporte a la célula.', 0.08, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_vegetal_cloroplasto', 'cell_vegetal', 'Cloroplasto', 'Realiza la fotosíntesis para producir energía a partir de la luz.', 0.7, 0.35);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_vegetal_vacuola', 'cell_vegetal', 'Vacuola central', 'Almacena agua y nutrientes, y da rigidez a la planta.', 0.5, 0.75);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_bacteriana_adn', 'cell_bacteriana', 'ADN libre', 'El material genético flota libremente, sin núcleo que lo envuelva.', 0.5, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_bacteriana_pared', 'cell_bacteriana', 'Pared celular', 'Protege a la bacteria del medio externo.', 0.1, 0.5);
INSERT INTO cell_structures (id, cellModelId, name, function, xPercent, yPercent) VALUES ('cell_bacteriana_flagelo', 'cell_bacteriana', 'Flagelo', 'Una cola que le permite moverse en el agua.', 0.9, 0.5);

-- Sistemas del cuerpo (6) y órganos (18)
INSERT INTO body_systems (id, name, description) VALUES ('sys_digestivo', 'Sistema digestivo', 'Transforma los alimentos en energía utilizable.');
INSERT INTO body_systems (id, name, description) VALUES ('sys_circulatorio', 'Sistema circulatorio', 'Transporta sangre, oxígeno y nutrientes por todo el cuerpo.');
INSERT INTO body_systems (id, name, description) VALUES ('sys_respiratorio', 'Sistema respiratorio', 'Permite el intercambio de oxígeno y dióxido de carbono.');
INSERT INTO body_systems (id, name, description) VALUES ('sys_nervioso', 'Sistema nervioso', 'Controla el cuerpo mediante señales eléctricas.');
INSERT INTO body_systems (id, name, description) VALUES ('sys_oseo', 'Sistema óseo', 'Da estructura y protección al cuerpo.');
INSERT INTO body_systems (id, name, description) VALUES ('sys_muscular', 'Sistema muscular', 'Permite el movimiento del cuerpo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_digestivo_organ_1', 'sys_digestivo', 'Estómago', 'Descompone el alimento con jugos digestivos.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_digestivo_organ_2', 'sys_digestivo', 'Intestino delgado', 'Absorbe los nutrientes hacia la sangre.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_digestivo_organ_3', 'sys_digestivo', 'Hígado', 'Produce bilis y filtra sustancias de la sangre.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_circulatorio_organ_1', 'sys_circulatorio', 'Corazón', 'Bombea la sangre por todo el cuerpo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_circulatorio_organ_2', 'sys_circulatorio', 'Venas', 'Llevan la sangre de vuelta al corazón.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_circulatorio_organ_3', 'sys_circulatorio', 'Arterias', 'Llevan la sangre con oxígeno desde el corazón.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_respiratorio_organ_1', 'sys_respiratorio', 'Pulmones', 'Intercambian oxígeno y dióxido de carbono con la sangre.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_respiratorio_organ_2', 'sys_respiratorio', 'Tráquea', 'Conduce el aire hacia los pulmones.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_respiratorio_organ_3', 'sys_respiratorio', 'Diafragma', 'Músculo que ayuda a inhalar y exhalar aire.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_nervioso_organ_1', 'sys_nervioso', 'Cerebro', 'Centro de control de pensamientos y movimientos.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_nervioso_organ_2', 'sys_nervioso', 'Médula espinal', 'Transporta señales entre el cerebro y el cuerpo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_nervioso_organ_3', 'sys_nervioso', 'Nervios', 'Ramificaciones que llevan señales a cada parte del cuerpo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_oseo_organ_1', 'sys_oseo', 'Cráneo', 'Protege el cerebro.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_oseo_organ_2', 'sys_oseo', 'Columna vertebral', 'Sostiene el cuerpo y protege la médula espinal.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_oseo_organ_3', 'sys_oseo', 'Fémur', 'El hueso más largo y fuerte del cuerpo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_muscular_organ_1', 'sys_muscular', 'Bíceps', 'Flexiona el brazo.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_muscular_organ_2', 'sys_muscular', 'Cuádriceps', 'Permite estirar la pierna al caminar o correr.');
INSERT INTO body_organs (id, bodySystemId, name, function) VALUES ('sys_muscular_organ_3', 'sys_muscular', 'Corazón (músculo cardíaco)', 'Se contrae sin descanso durante toda la vida.');

-- Experimentos (10/10)
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_micromundo_01', 'micromundo', 1, '¿Qué pasa si el agua de la charca se calienta demasiado?', 'Ajusta la temperatura del agua y observa cómo reaccionan los microorganismos.', 'Temperatura del agua', '°C', 0, 40, 15, 25, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_micromundo_02', 'micromundo', 2, '¿Qué pasa si la Euglena no recibe suficiente luz?', 'Ajusta las horas de luz solar que recibe el agua del estanque.', 'Horas de luz solar', 'horas', 0, 12, 6, 10, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_bosque_de_vida_01', 'bosque_de_vida', 1, '¿Qué pasa si una planta recibe menos luz?', 'Ajusta las horas de luz que recibe una planta del bosque cada día.', 'Horas de luz al día', 'horas', 0, 12, 6, 10, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_bosque_de_vida_02', 'bosque_de_vida', 2, '¿Qué pasa si llueve muy poco en el bosque?', 'Ajusta la cantidad de lluvia semanal que recibe el bosque.', 'Litros de lluvia por semana', 'litros', 0, 50, 20, 35, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_oceano_profundo_01', 'oceano_profundo', 1, '¿Qué pasa si el agua del mar se contamina?', 'Ajusta el nivel de contaminación del agua alrededor del arrecife.', 'Nivel de contaminación', 'nivel', 0, 10, 0, 3, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_oceano_profundo_02', 'oceano_profundo', 2, '¿Qué pasa si baja la temperatura del océano?', 'Ajusta la temperatura del agua donde vive el arrecife.', 'Temperatura del agua', '°C', 0, 30, 10, 20, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_cuerpo_humano_01', 'cuerpo_humano', 1, '¿Qué pasa si el cuerpo no recibe suficiente agua?', 'Ajusta cuántos vasos de agua toma el cuerpo al día.', 'Vasos de agua al día', 'vasos', 0, 12, 6, 8, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_cuerpo_humano_02', 'cuerpo_humano', 2, '¿Qué pasa si el cuerpo no descansa lo suficiente?', 'Ajusta cuántas horas duerme el cuerpo cada noche.', 'Horas de sueño', 'horas', 0, 12, 8, 10, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_ecosistemas_01', 'ecosistemas', 1, '¿Qué pasa si desaparecen los descomponedores?', 'Ajusta cuántos descomponedores hay en el ecosistema.', 'Cantidad de descomponedores', 'individuos', 0, 10, 3, 6, 30);
INSERT INTO experiments (id, environmentId, orderIndex, question, description, variableName, variableUnit, variableMin, variableMax, idealMin, idealMax, rewardXp) VALUES ('exp_ecosistemas_02', 'ecosistemas', 2, '¿Qué pasa si hay demasiados depredadores?', 'Ajusta cuántos depredadores hay en el ecosistema.', 'Cantidad de depredadores', 'individuos', 0, 10, 1, 4, 30);

-- Piezas del Constructor Biológico (16/16)
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('forma_redonda', 'FORMA', 'Forma redonda', 'Cuerpo esférico que resiste bien la presión del agua.', 'micromundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('forma_alargada', 'FORMA', 'Forma alargada', 'Cuerpo estilizado, ideal para nadar largas distancias.', 'oceano_profundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('forma_ramificada', 'FORMA', 'Forma ramificada', 'Se extiende en ramas finas para explorar el terreno.', 'bosque_de_vida');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('forma_plana', 'FORMA', 'Forma plana', 'Cuerpo en forma de disco, fácil de transportar por el flujo.', 'cuerpo_humano');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('mov_cilios', 'MOVIMIENTO', 'Cilios', 'Pequeños pelos que baten el agua para desplazarse.', 'micromundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('mov_aletas', 'MOVIMIENTO', 'Aletas', 'Permiten nadar con fuerza en aguas abiertas.', 'oceano_profundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('mov_esporas_viento', 'MOVIMIENTO', 'Esporas al viento', 'Se dispersan llevadas por el viento del bosque.', 'bosque_de_vida');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('mov_fija', 'MOVIMIENTO', 'Fija al sustrato', 'Permanece en un lugar reciclando lo que la rodea.', 'ecosistemas');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('alim_fotosintesis', 'ALIMENTACION', 'Fotosíntesis', 'Produce su propio alimento a partir de la luz.', 'bosque_de_vida');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('alim_filtra_particulas', 'ALIMENTACION', 'Filtra partículas', 'Cuela el agua para atrapar partículas de alimento.', 'oceano_profundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('alim_absorbe_nutrientes', 'ALIMENTACION', 'Absorbe nutrientes', 'Toma nutrientes directamente del medio que la rodea.', 'cuerpo_humano');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('alim_descompone', 'ALIMENTACION', 'Descompone materia', 'Recicla materia orgánica en descomposición.', 'ecosistemas');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('adapt_resiste_sequia', 'ADAPTACION', 'Resiste la sequía', 'Puede sobrevivir largos periodos sin agua.', 'ecosistemas');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('adapt_resiste_frio', 'ADAPTACION', 'Resiste el frío extremo', 'Tolera temperaturas muy bajas sin dañarse.', 'oceano_profundo');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('adapt_produce_toxinas', 'ADAPTACION', 'Produce toxinas defensivas', 'Se protege de depredadores con sustancias propias.', 'bosque_de_vida');
INSERT INTO creature_part_options (id, category, name, description, bestEnvironmentId) VALUES ('adapt_repara_rapido', 'ADAPTACION', 'Se repara rápido', 'Puede regenerarse o repararse en poco tiempo.', 'cuerpo_humano');

-- Tareas del Analizador (30/30)
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_01', 'micromundo', 'CATEGORIA', 'Clasifica los seres vivos de Micromundo', 'Agrupa cada hallazgo en su reino: planta, animal, microorganismo u hongo.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 15);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_02', 'micromundo', 'HABITAT', '¿Dónde vive cada uno? Micromundo', 'Relaciona cada ser vivo con el lugar donde habita.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 18);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_03', 'micromundo', 'DIETA', '¿De qué se alimentan? Micromundo', 'Averigua qué come cada uno de los seres vivos que descubriste.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 21);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_04', 'micromundo', 'RAREZA', 'Rarezas de Micromundo', 'Decide qué tan difícil es encontrar cada hallazgo.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 24);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_05', 'micromundo', 'MIXTO', 'Repaso mixto de Micromundo', 'Preguntas variadas sobre todo lo que descubriste en la zona.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 27);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_micromundo_06', 'micromundo', 'MIXTO', 'Desafío final de Micromundo', 'El reto completo: grupo, hábitat, alimentación y rareza.', 'disc_paramecio|disc_ameba|disc_euglena|disc_levadura|disc_tardigrado|disc_diatomea', 30);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_01', 'bosque_de_vida', 'CATEGORIA', 'Clasifica los seres vivos de Bosque de Vida', 'Agrupa cada hallazgo en su reino: planta, animal, microorganismo u hongo.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 15);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_02', 'bosque_de_vida', 'HABITAT', '¿Dónde vive cada uno? Bosque de Vida', 'Relaciona cada ser vivo con el lugar donde habita.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 18);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_03', 'bosque_de_vida', 'DIETA', '¿De qué se alimentan? Bosque de Vida', 'Averigua qué come cada uno de los seres vivos que descubriste.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 21);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_04', 'bosque_de_vida', 'RAREZA', 'Rarezas de Bosque de Vida', 'Decide qué tan difícil es encontrar cada hallazgo.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 24);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_05', 'bosque_de_vida', 'MIXTO', 'Repaso mixto de Bosque de Vida', 'Preguntas variadas sobre todo lo que descubriste en la zona.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 27);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_bosque_de_vida_06', 'bosque_de_vida', 'MIXTO', 'Desafío final de Bosque de Vida', 'El reto completo: grupo, hábitat, alimentación y rareza.', 'disc_helecho|disc_seta_amanita|disc_conejo|disc_zorro|disc_mariposa|disc_buho', 30);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_01', 'oceano_profundo', 'CATEGORIA', 'Clasifica los seres vivos de Océano Profundo', 'Agrupa cada hallazgo en su reino: planta, animal, microorganismo u hongo.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 15);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_02', 'oceano_profundo', 'HABITAT', '¿Dónde vive cada uno? Océano Profundo', 'Relaciona cada ser vivo con el lugar donde habita.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 18);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_03', 'oceano_profundo', 'DIETA', '¿De qué se alimentan? Océano Profundo', 'Averigua qué come cada uno de los seres vivos que descubriste.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 21);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_04', 'oceano_profundo', 'RAREZA', 'Rarezas de Océano Profundo', 'Decide qué tan difícil es encontrar cada hallazgo.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 24);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_05', 'oceano_profundo', 'MIXTO', 'Repaso mixto de Océano Profundo', 'Preguntas variadas sobre todo lo que descubriste en la zona.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 27);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_oceano_profundo_06', 'oceano_profundo', 'MIXTO', 'Desafío final de Océano Profundo', 'El reto completo: grupo, hábitat, alimentación y rareza.', 'disc_alga_marina|disc_coral|disc_medusa|disc_pulpo|disc_estrella_mar|disc_pez_payaso', 30);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_01', 'cuerpo_humano', 'CATEGORIA', 'Clasifica los seres vivos de Cuerpo Humano', 'Agrupa cada hallazgo en su reino: planta, animal, microorganismo u hongo.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 15);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_02', 'cuerpo_humano', 'HABITAT', '¿Dónde vive cada uno? Cuerpo Humano', 'Relaciona cada ser vivo con el lugar donde habita.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 18);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_03', 'cuerpo_humano', 'DIETA', '¿De qué se alimentan? Cuerpo Humano', 'Averigua qué come cada uno de los seres vivos que descubriste.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 21);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_04', 'cuerpo_humano', 'RAREZA', 'Rarezas de Cuerpo Humano', 'Decide qué tan difícil es encontrar cada hallazgo.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 24);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_05', 'cuerpo_humano', 'MIXTO', 'Repaso mixto de Cuerpo Humano', 'Preguntas variadas sobre todo lo que descubriste en la zona.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 27);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_cuerpo_humano_06', 'cuerpo_humano', 'MIXTO', 'Desafío final de Cuerpo Humano', 'El reto completo: grupo, hábitat, alimentación y rareza.', 'disc_globulo_rojo|disc_globulo_blanco|disc_neurona|disc_celula_muscular|disc_plaqueta', 30);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_01', 'ecosistemas', 'CATEGORIA', 'Clasifica los seres vivos de Ecosistemas', 'Agrupa cada hallazgo en su reino: planta, animal, microorganismo u hongo.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 15);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_02', 'ecosistemas', 'HABITAT', '¿Dónde vive cada uno? Ecosistemas', 'Relaciona cada ser vivo con el lugar donde habita.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 18);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_03', 'ecosistemas', 'DIETA', '¿De qué se alimentan? Ecosistemas', 'Averigua qué come cada uno de los seres vivos que descubriste.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 21);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_04', 'ecosistemas', 'RAREZA', 'Rarezas de Ecosistemas', 'Decide qué tan difícil es encontrar cada hallazgo.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 24);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_05', 'ecosistemas', 'MIXTO', 'Repaso mixto de Ecosistemas', 'Preguntas variadas sobre todo lo que descubriste en la zona.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 27);
INSERT INTO challenges (id, environmentId, type, title, instructions, relatedDiscoveryIds, rewardXp) VALUES ('cha_ecosistemas_06', 'ecosistemas', 'MIXTO', 'Desafío final de Ecosistemas', 'El reto completo: grupo, hábitat, alimentación y rareza.', 'disc_pasto|disc_leon|disc_nenufar|disc_hongo_reciclador', 30);

-- Coleccionables (15/15)
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_primer_descubrimiento', 'Primer Descubrimiento', 'Descubriste tu primer hallazgo en el microscopio.', 'col_primer_descubrimiento', 'DESCUBRIMIENTOS_TOTALES', 1, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_coleccionista_10', 'Coleccionista Curioso', 'Descubriste 10 hallazgos distintos.', 'col_coleccionista_10', 'DESCUBRIMIENTOS_TOTALES', 10, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_coleccionista_20', 'Coleccionista Experto', 'Descubriste 20 hallazgos distintos.', 'col_coleccionista_20', 'DESCUBRIMIENTOS_TOTALES', 20, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_museo_completo', 'Museo Completo', 'Descubriste los 30 hallazgos del laboratorio.', 'col_museo_completo', 'DESCUBRIMIENTOS_TOTALES', 30, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_primer_experimento', 'Primer Experimento', 'Completaste tu primer experimento biológico.', 'col_primer_experimento', 'EXPERIMENTOS_REALIZADOS', 1, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_cientifico_experimentado', 'Científico Experimentado', 'Completaste 10 experimentos biológicos.', 'col_cientifico_experimentado', 'EXPERIMENTOS_REALIZADOS', 10, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_primera_criatura', 'Primera Criatura', 'Creaste tu primera criatura microscópica.', 'col_primera_criatura', 'CRIATURAS_CREADAS', 1, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_creador_criaturas', 'Creador de Criaturas', 'Creaste 5 criaturas distintas.', 'col_creador_criaturas', 'CRIATURAS_CREADAS', 5, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_analista_10', 'Analista Aplicado', 'Superaste 10 tareas del Analizador.', 'col_analista_10', 'ANALISIS_SUPERADOS', 10, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_analista_20', 'Analista Experto', 'Superaste 20 tareas del Analizador.', 'col_analista_20', 'ANALISIS_SUPERADOS', 20, NULL);
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_ambiente_micromundo', 'Maestro del Micromundo', 'Completaste toda la colección del Micromundo.', 'col_ambiente_micromundo', 'AMBIENTE_COMPLETO', 100, 'micromundo');
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_ambiente_bosque', 'Guardián del Bosque', 'Completaste toda la colección del Bosque de Vida.', 'col_ambiente_bosque', 'AMBIENTE_COMPLETO', 100, 'bosque_de_vida');
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_ambiente_oceano', 'Explorador del Océano', 'Completaste toda la colección del Océano Profundo.', 'col_ambiente_oceano', 'AMBIENTE_COMPLETO', 100, 'oceano_profundo');
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_ambiente_cuerpo', 'Conocedor del Cuerpo', 'Completaste toda la colección del Cuerpo Humano.', 'col_ambiente_cuerpo', 'AMBIENTE_COMPLETO', 100, 'cuerpo_humano');
INSERT INTO lab_collectibles (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('col_legendario', 'Cazador de Leyendas', 'Descubriste un hallazgo legendario.', 'col_legendario', 'RAREZA_LEGENDARIA', 1, NULL);

-- Mejoras del laboratorio (8/8)
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_analizador', 'Analizador de Muestras', 'Desbloquea la herramienta Analizador en tu laboratorio.', 'up_analizador', 'DESCUBRIMIENTOS_TOTALES', 1, NULL);
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_diario_ampliado', 'Diario Ampliado', 'Tu Diario Científico gana más espacio para fotos y notas.', 'up_diario_ampliado', 'DESCUBRIMIENTOS_TOTALES', 5, NULL);
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_microscopio_avanzado', 'Microscopio Avanzado', 'Tu microscopio revela detalles más finos en cada muestra.', 'up_microscopio_avanzado', 'EXPERIMENTOS_REALIZADOS', 3, NULL);
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_constructor_biologico', 'Constructor Biológico', 'Desbloquea la mesa de creación de criaturas microscópicas.', 'up_constructor_biologico', 'DESCUBRIMIENTOS_TOTALES', 8, NULL);
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_zona_oceano', 'Zona: Océano Profundo', 'Se habilita la exploración del Océano Profundo.', 'up_zona_oceano', 'AMBIENTE_COMPLETO', 50, 'micromundo');
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_zona_cuerpo', 'Zona: Cuerpo Humano', 'Se habilita la exploración del Cuerpo Humano.', 'up_zona_cuerpo', 'AMBIENTE_COMPLETO', 50, 'bosque_de_vida');
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_acuario_decorativo', 'Acuario del Laboratorio', 'Una decoración nueva para tu laboratorio personal.', 'up_acuario_decorativo', 'DESCUBRIMIENTOS_TOTALES', 15, NULL);
INSERT INTO laboratory_upgrades (id, name, description, iconKey, criteriaType, criteriaValue, environmentId) VALUES ('up_rincon_investigador', 'Rincón del Investigador', 'Tu laboratorio gana un rincón especial de investigador.', 'up_rincon_investigador', 'RAREZA_LEGENDARIA', 1, NULL);

-- Perfil inicial (se crea automáticamente en el primer arranque)
INSERT INTO explorer_profile (id, alias, avatarKey, totalXp, onboardingCompleted, soundEnabled, hapticsEnabled, createdAtEpochMillis) VALUES (1, 'Joven Biólogo', 'avatar_explorador_1', 0, 0, 1, 1, 0);
